package example;

import io.offixa.pdfixa.core.content.ContentStream;
import io.offixa.pdfixa.core.document.PdfDocument;
import io.offixa.pdfixa.core.document.PdfPage;

import java.io.FileOutputStream;
import java.io.IOException;

public class BatchExample {

    public static void main(String[] args) throws IOException {
        int totalDocuments = 10;

        for (int i = 1; i <= totalDocuments; i++) {
            PdfDocument doc = new PdfDocument();
            PdfPage page = doc.addPage();
            ContentStream cs = page.getContent();

            page.drawTextBox(50, 740, 300, 28, "Helvetica-Bold", 22, "Document #" + i);
            page.drawTextBox(50, 712, 400, 14, "Helvetica", 11,
                    "Generated by PDFixa Batch Processor");

            drawLine(cs, 50, 700, 550, 700);

            page.drawTextBox(50, 674, 400, 16, "Helvetica", 13,
                    "Recipient: Customer " + i);
            page.drawTextBox(50, 654, 400, 16, "Helvetica", 13,
                    "Reference: BATCH-2026-" + String.format("%04d", i));
            page.drawTextBox(50, 634, 400, 16, "Helvetica", 13,
                    "Status: Completed");

            drawLine(cs, 50, 618, 550, 618);

            page.drawTextBox(50, 590, 500, 40, "Helvetica", 11,
                    "This is an auto-generated document (" + i + " of " + totalDocuments + "). " +
                    "Each PDF in this batch is created independently inside a simple loop.");

            String outputPath = "batch-output-" + String.format("%02d", i) + ".pdf";
            try (FileOutputStream fos = new FileOutputStream(outputPath)) {
                doc.save(fos);
            }
            System.out.println("Saved: " + outputPath);
        }

        System.out.println("Batch complete - " + totalDocuments + " PDFs generated.");
    }

    private static void drawLine(ContentStream cs, double x1, double y1, double x2, double y2) {
        cs.setLineWidth(0.5);
        cs.moveTo(x1, y1);
        cs.lineTo(x2, y2);
        cs.stroke();
    }
}
